// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTaGqCvdHatTZrL0xisvjYz38Dbmom6T8',
    appId: '1:251628205226:web:4b73c19eb1961eec404cd3',
    messagingSenderId: '251628205226',
    projectId: 'final-project-ff74e',
    authDomain: 'final-project-ff74e.firebaseapp.com',
    storageBucket: 'final-project-ff74e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo9wFXhhz5gWKetIGxOe6V6wb-AuyV4_s',
    appId: '1:251628205226:android:acb13bb77f874dcb404cd3',
    messagingSenderId: '251628205226',
    projectId: 'final-project-ff74e',
    storageBucket: 'final-project-ff74e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ6sDDhwn4GpZQoFvsbw6Ke2sL4FDxGlc',
    appId: '1:251628205226:ios:bf32c7a2efbc11b0404cd3',
    messagingSenderId: '251628205226',
    projectId: 'final-project-ff74e',
    storageBucket: 'final-project-ff74e.appspot.com',
    androidClientId: '251628205226-8bg7a0r1f7cn7t0hdtir8dj2vi0l7l31.apps.googleusercontent.com',
    iosClientId: '251628205226-nc8vln6eeojiujr5u4sr7sil4ck22mmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjectShoppingApp',
  );

}